name: Deploy Docker Images

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout (e.g., master)'
        required: true
        default: 'master'      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare release body
        run: |
          RELEASE_DATETIME=$(date -u +"%Y%m%dT%H%M%S")
          echo "RELEASE_TAG=$RELEASE_DATETIME" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lmshg
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push slim image linux/arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: lmshg/train-ticket-deploy:${{ env.RELEASE_TAG }}
          file: deploy-job/Dockerfile
          build-args: |
            LIGHTEN=1
          platforms: linux/arm64